travis:
  secure:
    BINSTAR_TOKEN: G2Rm3AKxaq4DHo0AeLNyj5j0rQ70oaABaMNjS+YMJXX+NBLMu0XW2T9d5HJHxSAwSvAPkTrRoTJBOE0ocFr+or/DgOC1amwWnsz7g8hQa7jvOOzCSKFnV4MdD+uHHcpmjY9vQMVEVJNy4fVjrAEDvBC1P06aaSCxSGnDo+a9gcZf5GzJhMcavVvFsQilUnizo69pwKb4jnzHusjnKCKYEbFt9jOhVCouL3xzOBQOYW4n6jGUn3el4RBiom3WZZJP4ze6CDWuJfjDAxd1K9GIkXYzTXql0R0X8sV/9joWewuPkwq2vjPAhTgLKYkOEhAcBVhUcmmOV/xXGKSypJY9wCq/zL1P8oo9/YFa/uspA7ixKHcdChY7p/R6Tdn2kLdBC/cFgJt3ipBfvXtnR/mMFZv+Qaa19swNo7pgqXt1/fwaNf0F6UfPFCLRLD/SKvrZ3rUOv0vxWx3WrPfIpvTLuMAouUV0vXMgsZX9PyoVVS+FTXWO2sID12irq2OzWa/0ZOrjJMgFwopBQvpkESKHs8vt9L0OKOItsBm7ixfLvtfrI0NUJS3WrG5U+8SVYPT48kOFqhdLhPgJvS+8EmMjj67T3AzFmBnRfmC7UrlkW5omI19HewARaX0wS7vFuRuck2znQzammu3ufzm/0lcMhmH2L7JSf0l3YRnUJn3lLb4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
